import express from 'express';
const router = express.Router();

router.get('/teaching/:subtopicId', async (req, res) => {
  try {
    const subtopicId = req.params.subtopicId;
    
    const blocks = [
      {
        type: 'paragraph',
        content: "Welcome to this lesson! This is mock teaching content generated by the backend."
      },
      {
        type: 'insight',
        content: "You can use this mock data to verify that your frontend renders the teaching canvas correctly."
      },
      {
        type: 'list',
        items: [
          "Verify the curriculum tree works",
          "Verify the teaching canvas renders blocks",
          "Test the question components"
        ]
      },
      {
        type: 'question',
        questionType: 'mcq',
        question: "Is the teaching API connected properly?",
        options: ["Yes", "No", "Maybe"],
        correctIndex: 0,
        explanations: {
          correct: "Correct! The frontend successfully fetched this data from the backend.",
          incorrect: ["Actually, it is working now!"]
        },
        hint: "The answer is Yes."
      }
    ];

    res.json({ blocks, cached: false, curriculum_id: "mock" });
  } catch (error) {
    res.status(500).json({ detail: error.message });
  }
});

router.post('/teaching/ask', async (req, res) => {
  res.json({ answer: "This is a stub teaching answer from the Node backend." });
});

export default router;
